apiVersion: v1
kind: Service
metadata:
    name: "anilak1-8868"
    labels:
        app: "anilak1-8868"
spec:
    type: LoadBalancer
    ports:
    - port: 245
      targetPort: 245
      protocol: TCP
      name: http
    selector:
        app: "anilak1-8868"