apiVersion: v1
kind: Service
metadata:
    name: "anilak1-a15d"
    labels:
        app: "anilak1-a15d"
spec:
    type: LoadBalancer
    ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: http
    selector:
        app: "anilak1-a15d"